---
title: "Collecting drone data"
author: "Noa Ratia"
date: "2024-03-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## A note on flight mission planning
The _throne_ package requires orthomosaic .tif-files that are construced using nadir thermal images of your field site. To collect these, you need to plan a flight mission with a drone that is equipped with a thermal camera. For the examples in this vignette, we use a DJI Matrice 200 V2 quadcopter, with a Zenmuse XT2 camera mounted. Note that thermal cameras usually have a much lower photo resolution and field of view than visual cameras, so a high vertical and horizontal photo overlap ratio is recommended for the mission, as well as a relatively high flight altitude (e.g. a minimum of 80%/80% and a mission altitude of 300 ft/90 m above ground level). This, of course, depends on the spatial scale of the studied landscape and the desired resolution thereof. Regardless, nake sure you're mission is built around the _thermal_ camera's field of view rather than the visual camera - especially if you're flying in a rugged landscape - otherwise you risk running into stitching issues when processing the photos! It's generally a good idea to extend the flight mission area to exceed the study site's boundaries by a few meters to compensate for this difference. 

## Collecting thermal imagery
The flight mission details will be very context dependent on your UAS and camera setup, but generally speaking, standard UAS mission planning etiquette applies to collecting data for use with _throne_:

* Abide by all local laws and regulations regarding flight altitude, airspace restrictions and drone registration requirements. Check with your local authorities what applies to you! For example, if you're flying in U.S. airspace, adhere to the **Code of Federal Regulations (CFR) Part 107**, and make sure you're in Class G airspace, unless you have explicit permission to fly elsewhere. You may also be required to have your drone registered for commercial use if it is used for research purposes.
* The default drone flight path ("zig-zag line") is generally fine for _throne_ mapping purposes. Avoid long, narrow flight paths to minimize banding issues, and aim to keep flight times relatively short to take a true "snapshot" of the thermal landscape.
* Fly under weather conditions that are typical to **your** study system, and strive towards distributing your flights across different times of the day, to maximize representation of OTM data.

One of the most important factors for maximizing the strength of your _throne_ model is to minimize geolocation errors of your photos. While some of this can be compensated through post-processing, deploying **ground control points (GCPs)** is one of the more common methods that can be used as a preventative measure to accurately georeference your flight missions. We recommend deploying a minimum of three GCPs per field site that you aim to survery - simple black-and-white square tiles that have known GPS locations works just fine - but it is crucial that these are deployed **before** any flights so that they are visible in photos from each mission. For more information on GCPs, PIX4D has a [great article](https://www.pix4d.com/blog/GCP-accuracy-drone-maps/) on how they correlate with the accuracy of drone maps.

## Processing flight data
After you have collected your thermal photos from multiple flights, you can begin photogrammetry to produce thermal orthomosaic images that can be used with the _throne_ package. There are plenty of software capable of doing this, and each comes with its own set of pros and cons. For our examples, we use [PIX4Dmapper](https://www.pix4d.com/product/pix4dmapper-photogrammetry-software/), yet this software might not be accessible for everyone. [OpenDroneMap](https://www.opendronemap.org/) offers a web-based, open-source and free solution, which we won't cover here, yet might be a valuable option for some users. Note also that PIX4D have an extensive online database on how to use the software (such as ["how-to" videos](https://support.pix4d.com/hc/en-us/articles/360032118251-Video-tutorials#PIX4Dmapper) and [articles](https://support.pix4d.com/hc/en-us/categories/360001503192)), ranging from how to load images to editing raster images. These may prove helpful if you haven't used the software before, or find something below guide unclear or confusing.

Regardless, start by opening up PIX4Dmapper. Then...

1. Create your project by clicking "New Project" under "File".
2. Navigate to the folder where you're flight mission photos are stored, and where you wish the project folder to be saved. It's generally a good approach to have one folder per flight mission, so that you can...
3. Select all the photos (visual **and** thermal images) from the flight mission, and only photos that are relevant to that specific flight.
4. When prompted, select the _Thermal Camera_ default processing template. This should be visible in the menu after you've added and loaded the photos to the project. For more information, see PIX4D's article [Processing Options Default Templates](https://support.pix4d.com/hc/en-us/articles/205319155-Processing-Options-Default-Templates#gsc.tab=0)
5. Ensure that the "Pixel Size" and the "Focal Length" values are correctly set for your camera model: on the menu bar, click Project > Image Properties Editor... and in the section Selected Camera Model, click Edit... For step-by-step instructions about how to modify the camera model, refer to PIX4D's article [How to use the Editing Camera Model Options](https://support.pix4d.com/hc/en-us/articles/202560169).
6. Before you begin processing, open "Processing Options" and navigate to _Keypoints Image Scale_ under "Initial Processing" and set it to Full; navigate to "Point Cloud and Mesh" and the Point Cloud and set the _Image Scale_ to 1 (original). These settings increase the density of keypoints and the resolution of the final product, at the cost of processing time. (You can leave these values unchanged, but note that the quality of the _throne_ model will likely be impacted.) If you wish, you can save this as a custom template for future _throne_ flight processes, by clicking "Save Template".
7. If you do not wish to use (or don't have access to any) ground control points, go ahead and  click "Start" on the Processing bar to begin processing your images. The thermal landscape map will be generated during the final step, "3. DSM, Orthomosaic, and Index.". Processing time depends on your PC specifications and the size of the project, but usually lasts a couple of hours. You can adjust the resources (GB of RAM and CPU threads) that PIX4Dmapper use under "Processing options". Note that the default is to use **all** your PC's available resources!

#### Note on GCPs
If you wish to include ground control points in your project, make sure to import these before you start processing. PIX4D has [a extensive how-to guides](https://support.pix4d.com/hc/en-us/articles/202558699-Using-GCPs-PIX4Dmapper) on this topic, which applies to generating raster images for _throne_ as well. Below are some general advice:

* In PIX4Dmapper, the easiest way to import ground control points is by loading a .csv-file that contains the latitude, longitude and altitude of your GCPs, using the "GCP/MTP Manager" after the first processing step ("Initial Processing") has been completed. Make sure your GCPs and project has the same coordinate system!
  * After you've loaded the GCP points, they will appear as "pins" in your point cloud, visible in the rayCloud viewer.
  * Manually match photos with the GCPs in which they are visible using the rayCloud editor. Refer to the [PIX4D documentation](https://support.pix4d.com/hc/en-us/articles/360000276046-How-to-import-and-mark-ground-control-points-GCPs-PIX4Dmapper) for more information. 
  * Continue by "Reoptimize" your project, under the "Process" drop-down menu and continue with the second and third processing steps.
* If you're using a DJI drone, you may encounter issues when importing the GCP coordinates from their .csv-file. If that is the case, *first* manually create tie points where you mark the GCPs in your photos (with identical names to their labels in the .csv-file) and *then* import the coordinates using the "GCP/MTP Manager". Finish by clicking "Rematch and Optimize", under the "Process" dropdown menu.

PIX4D will automatically create subfolders for each processing step of your project, contained in its main folder that you specified the directory for when loading in photos. Your final thermal orthomosaic image will be found under the project's subfolder named "3_dsm_ortho" and from there in "2_mosaic". There should be two .tif-files in the folder. Extract the one that is **not** the visual orthomosaic (i.e. non-black-and-white image). Export it to the directory where you will be building your _throne_ model!