---
title: "Collecting OTM data"
author: "Noa Ratia"
date: "2024-03-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Programming iButtons
Before deploying OTMs, each iButton needs to be individually programmed using a USB-connected 1-Wire adapter, such as the [DS9490B](https://www.ibuttonlink.com/products/ds9490b), or [DS1402D-DR8+](https://www.ibuttonlink.com/products/ds1402d-dr8). Once the iButton reader is connected, the iButton can be inserted for both programming and downloading data.

To begin, download the OneWireViewer (iButton) programming software, by Analog devices. A link to the software's download page can be found [here](https://www.analog.com/en/resources/evaluation-hardware-and-software/1-wire-sdks/download-1wire-ibutton-drivers.html), and an instructional video how to get started can be found [here](https://www.analog.com/en/resources/media-center/videos/6313216031112.html). Note that the software is a Java-based applet, so you'll need to [install Java](https://www.java.com/en/download/) if you haven't already. Insert the iButton reader into an available USB-port, install the software and launch it. Then...

1. If it's the first time you're launching the software, you might have to select which USB port the reader is connected to. Choose a USB-port from the drop-down list if prompted.
2. Insert an iButton into the reader. If the iButton is working it’ll show up as a device with a serial number in the software's left window panel; if the iButton does not show up then it is likely dead or malfunctioning.
3. Select the iButton in the list of devices on the left, and go to the "Thermochron" tab.
4. Click "Start new mission" to start programming the iButton.
5. Check the box that says “Synchronize Real-time Clock”. This will make sure the iButton's internal real-time clock is synchronized with the time on your PC.
6. Enter the "Sampling Rate", in minutes.
7. Enter "Mission Start Delay", which will be the time before the first data sample will be collected. Note that this is in *minutes*; for example, if you wish to start recording data in 24 hours, enter "1440" as the delay value.
8. Make sure "Enable Rollover" is _not_ enabled, unless you want your data to be overwritten once the memory is full. Typically, the iButton can hold 2048 measurements. You'll need to do some maths to figure out when the memory will be full / when the OTMs will have to be retrieved and redeployed!

After you've gone through these steps, the line that reads "Is Mission Active?" should change from "False" to "True" within a second or two. You'll also see "First sample not yet collected". Your iButton is ready to be inserted into an OTM and deployed in the field.

## Reading iButton data
The process for downloading data from the iButtons is very similar to the programming process. Assuming you have the 1-Wire adapter connected, insert the iButton into the reader and start up the OneWireViewer software.

1. Select your iButton in the software's left window pane
2. Navigate to the "Thermocron" tab, then "Temperatures".
3. The reader will take a second to display in a graph of the temperatures plotted over time. Once the graph shows up, right-click anywhere within the graph window for a drop-down menu to appear.
4. Select "Save Data to .csv File". Save the file in the directory you work with your _throne_ data.

The data will remain on the iButton until it is programmed anew. Note that once you start a new mission, the old mission data will be lost, so make sure you have all data downloaded before redeployment.
